### ISSUE TITLE
speculative.test macros cannot be used in node repl

### ISSUE THREAD

**Issue by borkdude** [slipset/speculative#95]
Repro:

```
$ clj -Sdeps '{:deps {org.clojure/clojurescript {:mvn/version "1.10.439"} org.clojure/test.check {:mvn/version "RELEASE"} speculative {:mvn/version "0.0.2"}}}' -m cljs.main -re node -r
ClojureScript 1.10.439
cljs.user=> (require '[speculative.test :as test])
nil
cljs.user=> (test/gentest `str nil {:num-tests 1})
WARNING: No such namespace: clojure.spec.test.alpha, could not locate clojure/spec/test/alpha.cljs, clojure/spec/test/alpha.cljc, or JavaScript source providing "clojure.spec.test.alpha" at line 1 <cljs repl>
WARNING: Use of undeclared Var clojure.spec.test.alpha/*instrument-enabled* at line 1 <cljs repl>
WARNING: clojure.spec.test.alpha/*instrument-enabled* not declared ^:dynamic at line 1 <cljs repl>
WARNING: No such namespace: clojure.spec.test.alpha, could not locate clojure/spec/test/alpha.cljs, clojure/spec/test/alpha.cljc, or JavaScript source providing "clojure.spec.test.alpha" at line 1 <cljs repl>
WARNING: Use of undeclared Var clojure.spec.test.alpha/*instrument-enabled* at line 1 <cljs repl>
WARNING: No such namespace: clojure.spec.test.alpha, could not locate clojure/spec/test/alpha.cljs, clojure/spec/test/alpha.cljc, or JavaScript source providing "clojure.spec.test.alpha" at line 1 <cljs repl>
WARNING: Use of undeclared Var clojure.spec.test.alpha/*instrument-enabled* at line 1 <cljs repl>
WARNING: No such namespace: clojure.spec.test.alpha, could not locate clojure/spec/test/alpha.cljs, clojure/spec/test/alpha.cljc, or JavaScript source providing "clojure.spec.test.alpha" at line 1 <cljs repl>
WARNING: Use of undeclared Var clojure.spec.test.alpha/*instrument-enabled* at line 1 <cljs repl>
repl:31
throw e__6600__auto__;
^

TypeError: Cannot read property 'test' of undefined
    at repl:1:167
    at repl:19:4
    at repl:27:3
    at repl:32:4
    at Script.runInThisContext (vm.js:96:20)
    at Object.runInThisContext (vm.js:303:38)
    at Domain.<anonymous> ([stdin]:76:38)
    at Domain.run (domain.js:343:14)
    at Socket.<anonymous> ([stdin]:73:29)
    at Socket.emit (events.js:182:13)
```

**Comment by borkdude** [comment]
Planck (self-hosted) REPL does not have this problem.

**Comment by borkdude** [comment]
Small repro: https://gist.github.com/borkdude/145d9433d9e8cc386d40495849b0b3c8
